---
# Docker Compose Application Deployment

- name: Deploy Application with Docker Compose
  hosts: docker_hosts
  become: yes
  
  vars:
    app_name: myapp
    app_path: /opt/{{ app_name }}
    app_repo: https://github.com/company/myapp.git
    app_version: main
    app_env: production
    
    # Environment variables for containers
    app_environment:
      NODE_ENV: "{{ app_env }}"
      DATABASE_URL: "postgresql://{{ db_user }}:{{ db_password }}@db:5432/{{ db_name }}"
      REDIS_URL: "redis://redis:6379"
      SECRET_KEY: "{{ vault_secret_key }}"
    
    # Database settings
    db_name: myapp
    db_user: myapp
    db_password: "{{ vault_db_password | default('changeme') }}"
  
  tasks:
    - name: Create application directory
      file:
        path: "{{ app_path }}"
        state: directory
        mode: '0755'
    
    - name: Clone/Update application repository
      git:
        repo: "{{ app_repo }}"
        dest: "{{ app_path }}"
        version: "{{ app_version }}"
        force: yes
      register: git_result
    
    - name: Create .env file
      template:
        src: templates/env.j2
        dest: "{{ app_path }}/.env"
        mode: '0600'
      no_log: true
    
    - name: Create docker-compose.yml
      template:
        src: templates/docker-compose.yml.j2
        dest: "{{ app_path }}/docker-compose.yml"
        mode: '0644'
    
    - name: Pull latest images
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        pull: always
      register: pull_result
    
    - name: Start application
      community.docker.docker_compose_v2:
        project_src: "{{ app_path }}"
        state: present
      register: compose_result
    
    - name: Wait for application to be ready
      uri:
        url: "http://localhost:3000/health"
        status_code: 200
      register: health_check
      until: health_check.status == 200
      retries: 30
      delay: 5
    
    - name: Show deployment status
      debug:
        msg: |
          ✅ Deployment successful!
          App: {{ app_name }}
          Version: {{ app_version }}
          Path: {{ app_path }}
          Health: OK
