---
- name: Install controller SSH key
  hosts: all
  gather_facts: false
  become: true

  vars:
    ssh_users:
      - vagrant
      - root
  
  tasks:
    - name: Add controller public key
      authorized_key:
        user: "{{ item }}"
        state: present
        key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"
      loop: "{{ ssh_users }}"
